# Generated by Django 4.2.5 on 2023-10-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_mensaje_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='agend',
            new_name='agent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_by',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('closed', 'Closed')], default='waiting', max_length=20),
        ),
    ]
