# Generated by Django 4.2.5 on 2023-09-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjera', 'Extranjera')], default='Nacional', max_length=10)),
                ('monto', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Beca',
            },
        ),
        migrations.CreateModel(
            name='Becas_Fav',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('facultad', 'facultad'), ('beca', 'beca')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_Becas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Facultad',
            },
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Entidad', 'Entidad'), ('Universidad', 'Universidad')], default='Universidad', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Universidad',
            },
        ),
        migrations.CreateModel(
            name='Union_U_F',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.facultad')),
                ('univeridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad_fav',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.facultad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='facultad',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_foraneas_Facultad'),
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.beca'),
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Fundacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.fundacion'),
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Union_U_F',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.union_u_f'),
        ),
        migrations.AddField(
            model_name='becas_fav',
            name='Configuracion_Becas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.configuracion_becas'),
        ),
        migrations.AddField(
            model_name='becas_fav',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beca',
            name='Documentos',
            field=models.ManyToManyField(to='mainPage.documentos'),
        ),
        migrations.AddField(
            model_name='beca',
            name='Requisitos',
            field=models.ManyToManyField(to='mainPage.requisitos'),
        ),
        migrations.AddConstraint(
            model_name='union_u_f',
            constraint=models.UniqueConstraint(fields=('univeridad', 'facultad'), name='unique_foraneas_union'),
        ),
        migrations.AddConstraint(
            model_name='configuracion_becas',
            constraint=models.UniqueConstraint(fields=('Union_U_F', 'Beca', 'Fundacion'), name='unique_foraneas_configuracion'),
        ),
        migrations.AddConstraint(
            model_name='becas_fav',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas', 'tipo'), name='unique_foraneas_favoritos'),
        ),
        migrations.AddConstraint(
            model_name='beca',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_foraneas_Beca'),
        ),
    ]
