# Generated by Django 4.1.5 on 2023-09-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_alter_beca_nombre_alter_documentos_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='becas_fav',
            name='unique_foraneas_favoritos',
        ),
        migrations.AddConstraint(
            model_name='becas_fav',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas', 'tipo'), name='unique_foraneas_favoritos_Beca'),
        ),
        migrations.AddConstraint(
            model_name='facultad_fav',
            constraint=models.UniqueConstraint(fields=('Facultad', 'Estudiante'), name='unique_foraneas_favoritos_Facultad'),
        ),
        migrations.AddConstraint(
            model_name='universidad_fav',
            constraint=models.UniqueConstraint(fields=('Universidad', 'Estudiante'), name='unique_foraneas_favoritos_Universidad'),
        ),
    ]
