# Generated by Django 4.2.5 on 2023-09-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('mainPage', '0002_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('descripcion', models.TextField()),
            ],
            bases=('schedule.event',),
        ),
    ]
