# Generated by Django 4.1.5 on 2023-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_remove_becas_fav_unique_foraneas_favoritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
