# Generated by Django 4.2.5 on 2023-09-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_remove_becas_fav_unique_foraneas_favoritos_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='becas_fav',
            name='unique_foraneas_favoritos_Beca',
        ),
        migrations.RemoveField(
            model_name='becas_fav',
            name='tipo',
        ),
        migrations.AddConstraint(
            model_name='becas_fav',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas'), name='unique_foraneas_favoritos_Beca'),
        ),
    ]
