# Generated by Django 4.2.5 on 2023-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_remove_becas_fav_unique_foraneas_favoritos_beca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beca',
            name='valor',
        ),
        migrations.AddField(
            model_name='beca',
            name='valor_duracion',
            field=models.CharField(default=100, max_length=500),
            preserve_default=False,
        ),
    ]
