# Generated by Django 4.2.5 on 2023-09-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_remove_beca_valor_beca_valor_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
