# Generated by Django 4.2.5 on 2023-09-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_beca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_becas/'),
        ),
    ]
