# Generated by Django 4.2.5 on 2023-10-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_beca_likes'),
        ('mainPage', '0004_publicacion_comentario'),
        ('mainPage', '0007_alter_beca_imagen'),
    ]

    operations = [
    ]
