# Generated by Django 4.2.5 on 2023-10-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_alter_beca_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='aplicacion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
