# Generated by Django 4.2.5 on 2023-10-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_rename_usuario_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
