# Generated by Django 4.1.5 on 2023-10-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_merge_0004_beca_likes_0007_alter_beca_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beca',
            name='imagen',
        ),
    ]
