# Generated by Django 4.2.5 on 2023-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_beca_aplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beca',
            name='imagen',
        ),
    ]
