# Generated by Django 4.2.5 on 2023-10-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_merge_20231002_2336'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='becas_fav',
            name='unique_foraneas_favoritos_Beca',
        ),
        migrations.RemoveField(
            model_name='beca',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='beca',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='beca',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='beca',
            name='valor_duracion',
        ),
        migrations.AddField(
            model_name='becas_fav',
            name='tipo',
            field=models.CharField(choices=[('facultad', 'facultad'), ('beca', 'beca')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='becas_fav',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas', 'tipo'), name='unique_foraneas_favoritos_Beca'),
        ),
    ]
