# Generated by Django 4.2.5 on 2023-10-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_publicacion_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.facultad'),
        ),
    ]
