# Generated by Django 4.2.5 on 2023-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_remove_becas_fav_unique_foraneas_favoritos_beca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjera', 'Extranjera')], default='Nacional', max_length=10),
        ),
        migrations.AddField(
            model_name='beca',
            name='valor_duracion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
