# Generated by Django 4.1.5 on 2023-10-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_publicacion_comentario'),
        ('mainPage', '0009_remove_beca_imagen'),
    ]

    operations = [
    ]
