# Generated by Django 4.2.5 on 2023-10-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_beca_tipo_beca_valor_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_becas/'),
        ),
    ]
