# Generated by Django 4.2.5 on 2023-10-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_alter_publicacion_facultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='Facultad',
        ),
    ]
