# Generated by Django 4.1.5 on 2023-10-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_remove_becas_fav_unique_foraneas_favoritos_beca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beca',
            name='likes',
        ),
    ]
