# Generated by Django 4.2.5 on 2023-10-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_beca_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beca',
            name='imagen',
        ),
    ]
