# Generated by Django 4.2.5 on 2023-10-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_beca_imagen'),
        ('mainPage', '0011_beca_imagen'),
    ]

    operations = [
    ]
