# Generated by Django 4.2.5 on 2023-11-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_remove_publicacion_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainPage.facultad'),
            preserve_default=False,
        ),
    ]
