# Generated by Django 4.1.5 on 2023-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
