# Generated by Django 4.2.5 on 2023-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_remove_beca_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_becas/'),
        ),
    ]
