# Generated by Django 4.2.5 on 2023-10-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_remove_publicacion_facultad'),
        ('mainPage', '0013_alter_calificacion_id'),
        ('mainPage', '0013_beca_imagen'),
    ]

    operations = [
    ]
