# Generated by Django 4.2.5 on 2023-10-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_merge_0010_beca_imagen_0011_beca_imagen'),
        ('mainPage', '0014_merge_20231019_1418'),
    ]

    operations = [
    ]
