# Generated by Django 4.2.6 on 2023-11-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0014_merge_20231019_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
