# Generated by Django 4.1.5 on 2023-11-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_publicacion_facultad'),
        ('mainPage', '0014_merge_20231019_1418'),
    ]

    operations = [
    ]
