# Generated by Django 4.2.5 on 2023-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0015_merge_20231019_2050'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='becas_fav',
            name='unique_foraneas_favoritos_Beca',
        ),
        migrations.RemoveField(
            model_name='becas_fav',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
        ),
        migrations.RemoveField(
            model_name='quizusuario',
            name='puntaje_total',
        ),
        migrations.AddConstraint(
            model_name='becas_fav',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas'), name='unique_foraneas_favoritos_Beca'),
        ),
    ]
