# Generated by Django 4.2.6 on 2023-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0016_archivos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
    ]
