# Generated by Django 4.2.5 on 2023-11-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0015_merge_20231102_1521'),
        ('mainPage', '0017_delete_archivos_archivo_nombre'),
    ]

    operations = [
    ]
