# Generated by Django 4.2.4 on 2023-11-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0021_oportunidad_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='etiquetas',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('medicina', 'Medicina'), ('economia', 'Economía')], default='otros', max_length=100),
        ),
    ]
