# Generated by Django 4.2.4 on 2023-11-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0022_alter_oportunidad_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
