# Generated by Django 4.2.4 on 2023-11-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0023_alter_oportunidad_etiquetas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidad',
            old_name='etiquetas',
            new_name='etiquetas_materias',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etiquetas_tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
