# Generated by Django 4.2.5 on 2023-11-15 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainPage', '0024_rename_etiquetas_oportunidad_etiquetas_materias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadAsocidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.oportunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
