# Generated by Django 4.2.4 on 2023-11-15 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0024_rename_etiquetas_oportunidad_etiquetas_materias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
