# Generated by Django 4.2.7 on 2023-11-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0025_oportunidad_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oportunidad', models.ManyToManyField(to='mainPage.oportunidad')),
            ],
        ),
    ]
