# Generated by Django 4.2.7 on 2023-11-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0027_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oportunidad',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainPage.oportunidad'),
        ),
    ]
