# Generated by Django 4.2.7 on 2023-11-15 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainPage', '0028_remove_userprofile_oportunidad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UsuarioOportunidad',
        ),
    ]
