# Generated by Django 4.2.7 on 2023-11-16 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainPage', '0029_rename_userprofile_usuariooportunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariooportunidad',
            name='user',
        ),
        migrations.AddField(
            model_name='usuariooportunidad',
            name='nuevo_campo',
            field=models.CharField(default='valor_predeterminado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuariooportunidad',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariooportunidad',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.oportunidad'),
        ),
    ]
