# Generated by Django 4.2.7 on 2023-11-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0031_empresas'),
        ('mainPage', '0031_remove_usuariooportunidad_nuevo_campo'),
    ]

    operations = [
    ]
