# Generated by Django 4.2.4 on 2023-11-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0031_empresas'),
        ('mainPage', '0031_remove_usuariooportunidad_nuevo_campo'),
    ]

    operations = [
    ]
