# Generated by Django 4.2.4 on 2023-11-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0032_merge_20231116_1603'),
        ('mainPage', '0032_merge_20231129_2138'),
    ]

    operations = [
    ]
